### ISSUE TITLE
Application.DecimalSeparator not available when using Powerpoint

### ISSUE THREAD

**Issue by djrolfes** [PGS62/VBA-CSV#5]
I am trying to use the library in powerpoint via VBA and the Application object of Powerpoint does not seem to contain the the .DecimalSeparator, that is used in the CSVRead function (line 32).
![image](https://github.com/PGS62/VBA-CSV/assets/115458319/16791b1b-b5cb-486f-8994-0ecb80637181)

**Comment by ws-garcia** [comment]
The library is Excel only.

**Comment by PGS62** [comment]
Hello @djrolfes

You will find that the [latest version](https://github.com/PGS62/VBA-CSV/releases/tag/v0.31) now works from both PowerPoint and Word, as well as Excel.
